# Basic info
baseurl: ""
url: "https://blog.erad.fr"
title: Blogerad
name: Najib Idrissi
author: Najib Idrissi # for jekyll-feed
email: najib.idrissi.kaitouni@gmail.com
description: A blog about math, operads, algebraic topology, and whatever else I can think about.
social:
  name: Najib Idrissi
  links:
    - https://github.com/nidrissi
    - https://math.stackexchange.com/users/10014/najib-idrissi
    - https://mathoverflow.net/users/36146/najib-idrissi
    - https://math.univ-lille1.fr/~idrissi/

# Build conf
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/
excerpt_separator: <!--more-->
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging
  - jekyll-seo-tag
exclude: ["README.md"]
paginate: 5

# Tags
tag_page_layout: tag_page
tag_page_dir: tag

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
