baseURL = "https://idrissi.eu/"
title = "Najib Idrissi's homepage"
enableEmoji = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
paginate = 10
enableRobotsTXT = true

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[outputs]
  home = [ "HTML", "CSS", "RSS" ]
  section = [ "HTML", "RSS" ]

[blackfriday]
  hrefTargetBlank = false

[params]
  name = "Najib Idrissi"
  role = "Postdoc"
  organization = "ETH Zürich"
  organization_url = "https://www.ethz.ch"
  avatar = "photo.jpg"  # Specify an avatar image (in `static/img/` folder) or delete value to disable avatar.
  email = "najib.idrissi@math.ethz.ch"
  address = "ETH Zürich (D-MATH, Pool Group 5) – Rämistrasse 101 – 8092 Zürich – Switzerland"
  office = "Office: HG F27.4"
  office_hours = ""
  phone = ""
  skype = ""
  telegram = ""
  gpg_key_url = "/pubkey/"

  # Enable Keybase in Contact section by entering your keybase.io username.
  keybase = ""

  # Date format (refer to Go's date format: http://flippinggodateformat.com )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "2006-01-02"

  math = true

  # Enable native social sharing buttons?
  sharing = true

  css = ['academicons.css', 'bootstrap.min.css', 'style.css']
  js = ['jquery.slim.min.js', 'bootstrap.bundle.min.js', 'fontawesome-all.min.js', 'piwik.js']

  # Social/Academic Networking
  #
  # Icon pack "fa" includes the following social network icons:
  #
  #   twitter, weibo, linkedin, github, facebook, pinterest, google-plus,
  #   youtube, instagram, soundcloud
  #
  #   For email icon, use "fa" icon pack, "envelope" icon, and
  #   "mailto:your@email.com" as the link.
  #
  #   Full list: https://fortawesome.github.io/Font-Awesome/icons/
  #
  # Icon pack "ai" includes the following academic network icons:
  #
  #   google-scholar, arxiv, orcid, researchgate, mendeley
  #
  #   Full list: https://jpswalsh.github.io/academicons/


  [[params.social]]
    icon = "ai-arxiv"
    icon_pack = "ai"
    link = "https://arxiv.org/a/idrissi_n_1.html"

  [[params.social]]
    icon = "ai-google-scholar"
    icon_pack = "ai"
    link = "https://scholar.google.com/citations?user=Gwf_TxEAAAAJ"

  [[params.social]]
    icon = "fa-university"
    icon_pack = "fas"
    link = "https://mathscinet.ams.org/mathscinet/MRAuthorID/1233505"

  [[params.social]]
    icon = "ai-orcid"
    icon_pack = "ai"
    link = "https://orcid.org/0000-0001-7288-6726"

  [[params.social]]
    icon = "fa-stack-exchange"
    icon_pack = "fab"
    link = "https://math.stackexchange.com/users/10014/najib-idrissi"

  [[params.social]]
    icon = "fa-github"
    icon_pack = "fab"
    link = "https://github.com/nidrissi"

# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1
[[menu.main]]
  name = "CV"
  url = "/cv/"
  weight = 2

# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"

# Languages
#   Create a [languages.X] block for each language you want, where X is the language ID.

[Languages.en]
  languageCode = "en-us"
  weight = 1

[Languages.fr]
  languageCode = "fr-FR"
  weight = 2
  title = "Page perso de Najib Idrissi"
  role = "Postdoc"
  address = "ETH Zürich (D-MATH, Pool Group 5) – Rämistrasse 101 – 8092 Zürich – Suisse"
  office = "Bureau : HG F27.4"

  [[Languages.fr.menu.main]]
    name = "Accueil"
    url = "/fr/"
    weight = 1
  [[Languages.fr.menu.main]]
    name = "CV"
    url = "/fr/cv/"
    weight = 2

[permalinks]
  post = "/:year/:month/:day/:filename/"
