baseURL: https://idrissi.eu/
enableEmoji: true

# for RSS
copyright: © Najib Idrissi
author:
  name: Najib Idrissi
  email: najib.idrissi-kaitouni@imj-prg.fr
  role: Maître de conférences
  organizations:
    - "[Université Paris Diderot](https://www.univ-paris-diderot.fr/)"
    - "[Institut de Mathématiques de Jussieu-Paris Rive Gauche](https://www.imj-prg.fr/)"
  address:
    - Université Paris Diderot, IMJ-PRG
    - Bâtiment Sophie Germain
    - 8 place Aurélie Nemours
    - F-75013 Paris
    - France
  office: SG-7032
  phone:
    pretty: "(+33) 01 57 27 91 16"
    ugly: "+33157279116"

blackfriday:
  hrefTargetBlank: false
  fractions: false

params:
  home_counts:
    talk: 5
    post: 5

defaultContentLanguage: en
defaultContentLanguageInSubdir: true
languages:
  en:
    languageCode: en
    languageName: English
    title: "Najib Idrissi's page"
    params:
      date_format: Jan 2, 2006
  fr:
    languageCode: fr
    languageName: Français
    title: Page de Najib Idrissi
    params:
      date_format: 02/01/2006
    permalinks:
      post: /billet/:filename/
      research: /recherche/:filename/
      talk: /expose/:filename/
