baseurl = "https://operad.fr/"
title = "Najib Idrissi"
copyright = "&copy; 2017 Najib Idrissi"
theme = "academic"
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"

# Enable comments by entering your Disqus shortname
disqusShortname = ""

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = ""

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[blackfriday]
  hrefTargetBlank = true

[params]
  name = "Najib Idrissi"
  role = "PhD student"
  organization = "Université Lille 1"
  organization_url = "http://www.univ-lille1.fr"
  description = "I am Najib Idrissi, a PhD student in mathematics at the laboratoire Paul Painlevé, Université Lille 1."
  avatar = "photo.jpg"
  email = "najib.idrissi-kaitouni@math.univ-lille1.fr"
  address = " Université Lille 1 · Laboratoire Paul Painlevé · Cité Scientifique, Bâtiment M2 · 59655 Villeneuve d'Ascq Cedex · France (Office|Bureau: 110)"
  office_hours = ""
  phone = ""
  skype = ""
  telegram = ""

  # Enable Keybase in Contact section by entering your keybase.io username.
  keybase = ""

  # Date format (refer to Go's date format: http://flippinggodateformat.com )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "2006-01-02"

  # Enable global LaTeX math rendering?
  #   If false, you can enable it locally on a per page basis.
  math = true

  # Highlight.js options
  highlight = false
  highlight_languages = []

  # Enable native social sharing buttons?
  sharing = true

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  custom_css = []
  custom_js  = ['piwik.js']

  # Publication types.
  #   Used to categorize publications.
  #   The index of the publication type in the list is used as its unique numerical identifier.
  #   The numeric ID is used in a publication's frontmatter to categorize it.
  #   The language can be edited below.
  #   For multi-lingual sites, copy this block to each language section at the end of this file.
  publication_types = [
    'Uncategorized',  # 0
    'Conference proceedings',  # 1
    'Journal',  # 2
    'Work in progress',  # 3
    'Technical report',  # 4
    'Book',  # 5
    'Book chapter',  # 6
    'Thesis'  # 7
  ]

  # Social/Academic Networking
  #
  # Icon pack "fa" includes the following social network icons:
  #
  #   twitter, weibo, linkedin, github, facebook, pinterest, google-plus,
  #   youtube, instagram, soundcloud
  #
  #   For email icon, use "fa" icon pack, "envelope" icon, and
  #   "mailto:your@email.com" as the link.
  #
  #   Full list: https://fortawesome.github.io/Font-Awesome/icons/
  #
  # Icon pack "ai" includes the following academic network icons:
  #
  #   google-scholar, arxiv, orcid, researchgate, mendeley
  #
  #   Full list: https://jpswalsh.github.io/academicons/

  [[params.social]]
    icon = "envelope"
    icon_pack = "fa"
    link = "mailto:najib.idrissi-kaitouni@math.univ-lille1.fr"

  [[params.social]]
    icon = "arxiv"
    icon_pack = "ai"
    link = "https://arxiv.org/a/idrissi_n_1.html"

  [[params.social]]
    icon = "google-scholar"
    icon_pack = "ai"
    link = "https://scholar.google.com/citations?user=l23bjS4AAAAJ"

  [[params.social]]
    icon = "orcid"
    icon_pack = "ai"
    link = "https://orcid.org/0000-0001-7288-6726"

  [[params.social]]
    icon = "stack-exchange"
    icon_pack = "fa"
    link = "https://math.stackexchange.com/users/10014/najib-idrissi"

  [[params.social]]
    icon = "github"
    icon_pack = "fa"
    link = "https://github.com/nidrissi"


# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[menu.main]]
  name = "Home"
  url = "#about"
  weight = 1

[[menu.main]]
  name = "Research"
  url = "#research"
  weight = 3

[[menu.main]]
  name = "Blog"
  url = "#posts"
  weight = 5

[[menu.main]]
  name = "Contact"
  url = "#contact"
  weight = 2

[[menu.main]]
  name = "Talks"
  url = "#talks"
  weight = 4

# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"

# Languages
#   Create a [languages.X] block for each language you want, where X is the language ID.

# Configure the English version of the website.
[languages.en]
  languageCode = "en-us"

[permalinks]
  post = "/:year/:month/:day/:filename/"
