baseURL: https://idrissi.eu/
title: "Najib Idrissi's homepage"
enableEmoji: true
paginate: 10
enableRobotsTXT: true

defaultContentLanguage: en
defaultContentLanguageInSubdir: true

blackfriday:
  hrefTargetBlank: false

params:
  name: Najib Iᴅʀɪssɪ
  role: Maître de conférences
  organizations:
    - name: Université Paris Diderot
      url: https://www.univ-paris-diderot.fr/
    - name: Institut de Mathématiques de Jussieu-Paris Rive Gauche
      url: https://www.imj-prg.fr/
  avatar: photo.jpg
  email: najib.idrissi-kaitouni@imj-prg.fr
  address: Université Paris Diderot, IMJ-PRG – Bâtiment Sophie Germain – 8 place Aurélie Nemours – 75205 Paris Cedex 13 – France
  office: "Office SG-7032"
  phone:
    pretty: "(+33) 01 57 27 91 16"
    ugly: "+33157279116"

  date_format: 2006-01-02
  math: true
  css: ['bundle.css']
  js: ['jquery.slim.min.js', 'bootstrap.min.js']

taxonomies:
  tag: tags

languages:
  en:
    languageCode: en-us
    weight: 1
  fr:
    languageCode: fr-FR
    weight: 2
    title: Page de Najib Idrissi
    office: "Bureau SG-7032"
