baseURL: https://idrissi.eu/
title: "Najib Idrissi's homepage"
enableEmoji: true
paginate: 10
enableRobotsTXT: true

defaultContentLanguage: en
defaultContentLanguageInSubdir: true

outputs:
  home: ["HTML", "CSS", "RSS"]
  section: ["HTML", "RSS"]

blackfriday:
  hrefTargetBlank: false

permalinks:
  post: /:year/:month/:day/:filename/

params:
  name: Najib Idrissi
  role: Maître de conférences
  organizations:
    - name: Université Paris Diderot
      url: https://www.univ-paris-diderot.fr/
    - name: Institut de Mathématiques de Jussieu-Paris Rive Gauche
      url: https://www.imj-prg.fr/
  avatar: photo.jpg
  email: najib.idrissi-kaitouni@imj-prg.fr
  address: Université Paris Diderot, IMJ-PRG – Bâtiment Sophie Germain – 8 place Aurélie Nemours – 75205 Paris Cedex 13 – France
  office: "Office SG-7032"
  office_hours: ~
  phone:
    pretty: "(+33) 01 57 27 91 16"
    ugly: "+33157279116"
  skype: ~
  telegram: ~
  keybase: ~

  date_format: 2006-01-02
  math: true
  css: ['bundle.css']
  js: ['jquery.slim.min.js', 'bootstrap.min.js']

  social:
    - icon: '<i class="ai ai-arxiv ai-lg"></i>'
      link: "https://arxiv.org/a/idrissi_n_1.html"
    # - icon: '<i class="ai ai-google-scholar ai-lg"></i>'
    #   link: "https://scholar.google.com/citations?user=Gwf_TxEAAAAJ"
    # - icon: '<svg class="svg-inline--fa fa-university fa-w-16 fa-lg ai-lg" aria-hidden="true" data-prefix="fas" data-icon="university" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" data-fa-i2svg=""><path fill="currentColor" d="M496 128v16a8 8 0 0 1-8 8h-24v12c0 6.627-5.373 12-12 12H60c-6.627 0-12-5.373-12-12v-12H24a8 8 0 0 1-8-8v-16a8 8 0 0 1 4.941-7.392l232-88a7.996 7.996 0 0 1 6.118 0l232 88A8 8 0 0 1 496 128zm-24 304H40c-13.255 0-24 10.745-24 24v16a8 8 0 0 0 8 8h464a8 8 0 0 0 8-8v-16c0-13.255-10.745-24-24-24zM96 192v192H60c-6.627 0-12 5.373-12 12v20h416v-20c0-6.627-5.373-12-12-12h-36V192h-64v192h-64V192h-64v192h-64V192H96z"></path></svg>'
    #   link: "https://mathscinet.ams.org/mathscinet/MRAuthorID/1233505"
    - icon: '<i class="ai ai-orcid ai-lg"></i>'
      link: "https://orcid.org/0000-0001-7288-6726"
    - icon: '<i class="ai ai-mathoverflow ai-lg"></i>'
      link: "https://mathoverflow.net/users/36146/najib-idrissi"
    - icon: '<svg class="svg-inline--fa fa-stack-exchange fa-w-14 fa-lg ai-lg" aria-hidden="true" data-prefix="fab" data-icon="stack-exchange" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" data-fa-i2svg=""><path fill="currentColor" d="M17.7 332.3h412.7v22c0 37.7-29.3 68-65.3 68h-19L259.3 512v-89.7H83c-36 0-65.3-30.3-65.3-68v-22zm0-23.6h412.7v-85H17.7v85zm0-109.4h412.7v-85H17.7v85zM365 0H83C47 0 17.7 30.3 17.7 67.7V90h412.7V67.7C430.3 30.3 401 0 365 0z"></path></svg>'
      link: "https://math.stackexchange.com/users/10014/najib-idrissi"
    - icon: '<svg class="svg-inline--fa fa-github fa-w-16 fa-lg ai-lg" aria-hidden="true" data-prefix="fab" data-icon="github" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 496 512" data-fa-i2svg=""><path fill="currentColor" d="M165.9 397.4c0 2-2.3 3.6-5.2 3.6-3.3.3-5.6-1.3-5.6-3.6 0-2 2.3-3.6 5.2-3.6 3-.3 5.6 1.3 5.6 3.6zm-31.1-4.5c-.7 2 1.3 4.3 4.3 4.9 2.6 1 5.6 0 6.2-2s-1.3-4.3-4.3-5.2c-2.6-.7-5.5.3-6.2 2.3zm44.2-1.7c-2.9.7-4.9 2.6-4.6 4.9.3 2 2.9 3.3 5.9 2.6 2.9-.7 4.9-2.6 4.6-4.6-.3-1.9-3-3.2-5.9-2.9zM244.8 8C106.1 8 0 113.3 0 252c0 110.9 69.8 205.8 169.5 239.2 12.8 2.3 17.3-5.6 17.3-12.1 0-6.2-.3-40.4-.3-61.4 0 0-70 15-84.7-29.8 0 0-11.4-29.1-27.8-36.6 0 0-22.9-15.7 1.6-15.4 0 0 24.9 2 38.6 25.8 21.9 38.6 58.6 27.5 72.9 20.9 2.3-16 8.8-27.1 16-33.7-55.9-6.2-112.3-14.3-112.3-110.5 0-27.5 7.6-41.3 23.6-58.9-2.6-6.5-11.1-33.3 2.6-67.9 20.9-6.5 69 27 69 27 20-5.6 41.5-8.5 62.8-8.5s42.8 2.9 62.8 8.5c0 0 48.1-33.6 69-27 13.7 34.7 5.2 61.4 2.6 67.9 16 17.7 25.8 31.5 25.8 58.9 0 96.5-58.9 104.2-114.8 110.5 9.2 7.9 17 22.9 17 46.4 0 33.7-.3 75.4-.3 83.6 0 6.5 4.6 14.4 17.3 12.1C428.2 457.8 496 362.9 496 252 496 113.3 383.5 8 244.8 8zM97.2 352.9c-1.3 1-1 3.3.7 5.2 1.6 1.6 3.9 2.3 5.2 1 1.3-1 1-3.3-.7-5.2-1.6-1.6-3.9-2.3-5.2-1zm-10.8-8.1c-.7 1.3.3 2.9 2.3 3.9 1.6 1 3.6.7 4.3-.7.7-1.3-.3-2.9-2.3-3.9-2-.6-3.6-.3-4.3.7zm32.4 35.6c-1.6 1.3-1 4.3 1.3 6.2 2.3 2.3 5.2 2.6 6.5 1 1.3-1.3.7-4.3-1.3-6.2-2.2-2.3-5.2-2.6-6.5-1zm-11.4-14.7c-1.6 1-1.6 3.6 0 5.9 1.6 2.3 4.3 3.3 5.6 2.3 1.6-1.3 1.6-3.9 0-6.2-1.4-2.3-4-3.3-5.6-2z"></path></svg>'
      link: "https://github.com/nidrissi"

menu:
  main:
    - name: CV
      url: /en/cv/
      weight: 2
    - name: Research
      url: /en/research/
      weight: 3
    - name: Teaching
      url: /en/enseignement/
      weight: 4

taxonomies:
  tag: tags
  category: categories

languages:
  en:
    languageCode: en-us
    weight: 1
  fr:
    languageCode: fr-FR
    weight: 2
    title: Page perso de Najib Idrissi
    office: "Bureau SG-7032"
    menu:
      main:
        - name: CV
          url: /fr/cv/
          weight: 2
        - name: Recherche
          url: /fr/research/
          weight: 3
        - name: Enseignement
          url: /fr/enseignement/
          weight: 4
