baseURL: https://idrissi.eu/
title: "Najib Idrissi's homepage"
enableEmoji: true

# for RSS
copyright: © Najib Idrissi
author:
  name: Najib Idrissi
  email: najib.idrissi-kaitouni@imj-prg.fr
  role: Maître de conférences
  organizations:
    - "[Université Paris Diderot](https://www.univ-paris-diderot.fr/)"
    - "[Institut de Mathématiques de Jussieu-Paris Rive Gauche](https://www.imj-prg.fr/)"
  address: Université Paris Diderot, IMJ-PRG // Bâtiment Sophie Germain // 8 place Aurélie Nemours // 75205 Paris Cedex 13 // France
  office: SG-7032
  phone:
    pretty: "(+33) 01 57 27 91 16"
    ugly: "+33157279116"

defaultContentLanguage: en
defaultContentLanguageInSubdir: true

blackfriday:
  hrefTargetBlank: false
  fractions: false
params:
  date_format: Jan 2, 2006
  home_counts:
    research: 7
    talk: 5
    post: 5

languages:
  en:
    languageCode: en-us
  fr:
    languageCode: fr-fr
    title: Page de Najib Idrissi
    params:
      date_format: 02/01/2006
    permalinks:
      research: /recherche/:filename/
      talk: /expose/:filename/
