baseURL = "https://idrissi.eu/"
title = "Najib Idrissi's homepage"
enableEmoji = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
paginate = 10
enableRobotsTXT = true

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[outputs]
  home = [ "HTML", "CSS", "RSS" ]
  section = [ "HTML", "RSS" ]

[blackfriday]
  hrefTargetBlank = false

[permalinks]
  post = "/:year/:month/:day/:filename/"

[params]
  name = "Najib Idrissi"
  role = "Postdoc"
  organization = "ETH Zürich"
  organization_url = "https://www.ethz.ch"
  avatar = "photo.jpg"
  email = "najib.idrissi@math.ethz.ch"
  address = "ETH Zürich (D-MATH, Pool Group 5) – Rämistrasse 101 – 8092 Zürich – Switzerland"
  office = "Office: HG F27.4"
  office_hours = ""
  phone = ""
  skype = ""
  telegram = ""
  keybase = ""
  gpg_key_url = "/pubkey/"

  date_format = "2006-01-02"

  math = true

  css = ['bundle.css']
  css_footer = ['bundle.footer.css']
  js = ['jquery.slim.min.js', 'bootstrap.min.js', 'piwik.js']

  [[params.social]]
    icon = "ai-arxiv"
    icon_pack = "ai"
    link = "https://arxiv.org/a/idrissi_n_1.html"

  [[params.social]]
    icon = "ai-google-scholar"
    icon_pack = "ai"
    link = "https://scholar.google.com/citations?user=Gwf_TxEAAAAJ"

  [[params.social]]
    icon = "fa-university"
    icon_pack = "fas"
    link = "https://mathscinet.ams.org/mathscinet/MRAuthorID/1233505"

  [[params.social]]
    icon = "ai-orcid"
    icon_pack = "ai"
    link = "https://orcid.org/0000-0001-7288-6726"

  [[params.social]]
    icon = "fa-stack-exchange"
    icon_pack = "fab"
    link = "https://math.stackexchange.com/users/10014/najib-idrissi"

  [[params.social]]
    icon = "fa-github"
    icon_pack = "fab"
    link = "https://github.com/nidrissi"

[[menu.main]]
  name = "Home"
  pre = "<i class=\"fas fa-home\"></i>"
  url = "/"
  weight = 1
[[menu.main]]
  name = "CV"
  url = "/cv/"
  weight = 2

[taxonomies]
  tag = "tags"
  category = "categories"

[Languages.en]
  languageCode = "en-us"
  weight = 1

[Languages.fr]
  languageCode = "fr-FR"
  weight = 2
  title = "Page perso de Najib Idrissi"
  role = "Postdoc"
  address = "ETH Zürich (D-MATH, Pool Group 5) – Rämistrasse 101 – 8092 Zürich – Suisse"
  office = "Bureau : HG F27.4"

  [[Languages.fr.menu.main]]
    name = "Accueil"
    pre = "<i class=\"fas fa-home\"></i>"
    url = "/fr/"
    weight = 1
  [[Languages.fr.menu.main]]
    name = "CV"
    url = "/fr/cv/"
    weight = 2
